language: go
go:
  - 1.3.1
  - tip
notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - coda.hale@gmail.com
